# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
# services "nginx-svc" was not valid:
# * spec.clusterIPs[0]: Invalid value: []string(nil): primary clusterIP can not be unset
#
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2021-03-05T20:13:39Z"
  labels:
    app: nginx
  name: nginx-svc
  namespace: default
  resourceVersion: "214138"
  uid: 9c700a7c-7b5b-48d5-b583-b07c0ae632d6
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  sessionAffinity: None
  type: NodePort 
