apiVersion: v1
kind: Service
metadata:
  name: nginx-mirror-svc
  namespace: mirroring
  labels:
    app: nginx
spec:
  ports:
  - name: http
    port: 8000
    targetPort: 80
  selector:
    app: nginx
